# -*- coding: utf-8 -*-
"""
Created on Tue Sep  8 11:14:17 2020

@author: javi8
"""

# import pyqtgraph.parametertree.parameterTypes as pTypes
import numpy as np

DefaultGains = {'DCGain': 10e3,
                'ACGain': 1e6,
                'GateGain': 2e6}

MuxOutputs = {
    # '8Cols': {'Col01': ('line0', 'line1'),
    #           'Col02': ('line2', 'line3'),
    #           'Col03': ('line4', 'line5'),
    #           'Col04': ('line6', 'line7'),
    #           'Col05': ('line8', 'line9'),
    #           'Col06': ('line10', 'line11'),
    #           'Col07': ('line12', 'line13'),
    #           'Col08': ('line14', 'line15'),
    #         },

    # '16Cols': {'Col05': ('line0', 'line1'),
    #            'Col06': ('line2', 'line3'),
    #            'Col08': ('line4', 'line5'),
    #            'Col07': ('line6', 'line7'),
    #            'Col02': ('line8', 'line9'),
    #            'Col04': ('line10', 'line11'),
    #            'Col01': ('line12', 'line13'),
    #            'Col03': ('line14', 'line15'),
    #            'Col16': ('line16', 'line17'),
    #            'Col15': ('line18', 'line19'),
    #            'Col13': ('line20', 'line21'),
    #            'Col14': ('line22', 'line23'),
    #            'Col11': ('line24', 'line25'),
    #            'Col09': ('line26', 'line27'),
    #            'Col12': ('line28', 'line29'),
    #            'Col10': ('line30', 'line31'),
    #            },

    # 'MB42':  {'Col10': ('line0', ),
    #           'Col09': ('line1', ),
    #           'Col12': ('line2', ),
    #           'Col11': ('line3', ),
    #           'Col15': ('line4', ),
    #           'Col16': ('line5', ),
    #           'Col13': ('line6', ),
    #           'Col14': ('line7', ),
    #           'Col02': ('line8', ),
    #           'Col01': ('line9', ),
    #           'Col04': ('line10', ),
    #           'Col03': ('line11', ),
    #           'Col07': ('line12', ),
    #           'Col08': ('line13', ),
    #           'Col05': ('line14', ),
    #           'Col06': ('line15', ),
    #           },

    # 'MoS2': {'Col04': ('line0', ),
    #          'Col01': ('line1', ),
    #          'Col02': ('line2', ),
    #          'Col03': ('line3', ),
    #          'Col08': ('line4', ),
    #          'Col05': ('line5', ),
    #          'Col07': ('line6', ),
    #          'Col06': ('line7', ),
    #          'Col09': ('line8', ),
    #          'Col12': ('line9', ),
    #          'Col11': ('line10', ),
    #          'Col10': ('line11', ),
    #          'Col13': ('line12', ),
    #          'Col16': ('line13', ),
    #          'Col15': ('line14', ),
    #          'Col14': ('line15', ),
    #             },

    '32Cols': {'Col01': None,
               'Col02': None,
               'Col03': None,
               'Col04': None,
               'Col05': None,
               'Col06': None,
               'Col07': None,
               'Col08': None,
               'Col09': None,
               'Col10': None,
               'Col11': None,
               'Col12': None,
               'Col13': None,
               'Col14': None,
               'Col15': None,
               'Col16': None,
               'Col17': None,
               'Col18': None,
               'Col19': None,
               'Col20': None,
               'Col21': None,
               'Col22': None,
               'Col23': None,
               'Col24': None,
               'Col25': None,
               'Col26': None,
               'Col27': None,
               'Col28': None,
               'Col29': None,
               'Col30': None,
               'Col31': None,
               'Col32': None,
               },
}


def DecoderDigital(n):
    if n < 1:
        return [[]]
    subtable = DecoderDigital(n - 1)
    return [row + [v] for row in subtable for v in [0, 1]]


def GetDecoderSignal():
    Decoder = DecoderDigital(5)
    Dec = np.array(Decoder, dtype=np.uint8)
    DOut = np.array([])
    IndexDigitalLines = {}

    index = 0
    DigIndex = 0

    for n in MuxOutputs['32Cols'].keys():
        Lout = np.ones((1, 5))
        IndexDigitalLines[DigIndex] = n
        Lout = Lout * Dec[index]
        DOut = np.vstack((DOut, Lout)) if DOut.size else Lout
        DigIndex += 1
        index += 1

    MuxSwitch = {'Columns': IndexDigitalLines,
                 'DigitalSignal': DOut,
                 'douts': ('port0/line9:15',), }

    return MuxSwitch


MainBoard = {'Gains': DefaultGains,
             'AnalogInputs': {'Ch01': ('ai0', 'ai8'),
                              'Ch02': ('ai1', 'ai9'),
                              'Ch03': ('ai2', 'ai10'),
                              'Ch04': ('ai3', 'ai11'),
                              'Ch05': ('ai4', 'ai12'),
                              'Ch06': ('ai5', 'ai13'),
                              'Ch07': ('ai6', 'ai14'),
                              'Ch08': ('ai7', 'ai15'),
                              'Ch09': ('ai16', 'ai24'),
                              'Ch10': ('ai17', 'ai25'),
                              'Ch11': ('ai18', 'ai26'),
                              'Ch12': ('ai19', 'ai27'),
                              'Ch13': ('ai20', 'ai28'),
                              'Ch14': ('ai21', 'ai29'),
                              'Ch15': ('ai22', 'ai30'),
                              'Ch16': ('ai23', 'ai31')
                              },
             'AnalogOutputs': {'Vs': 'ao1',
                               'Vds': 'ao0',
                               'Vg': 'ao2',
                               },
             }

MB42 = {'Gains': {'DCGain': 10e3,
                  'ACGain': 1e6,
                  },
        'AnalogInputs': {
            'Ch01': ('ai16', 'ai24'),
            'Ch02': ('ai17', 'ai25'),
            'Ch03': ('ai18', 'ai26'),
            'Ch04': ('ai19', 'ai27'),
            'Ch05': ('ai20', 'ai28'),
            'Ch06': ('ai21', 'ai29'),
            'Ch07': ('ai22', 'ai30'),
            'Ch08': ('ai23', 'ai31'),
            'Ch09': ('ai0', 'ai8'),
            'Ch10': ('ai1', 'ai9'),
            'Ch11': ('ai2', 'ai10'),
            'Ch12': ('ai3', 'ai11'),
            'Ch13': ('ai4', 'ai12'),
            'Ch14': ('ai5', 'ai13'),
            'Ch15': ('ai6', 'ai14'),
            'Ch16': ('ai7', 'ai15'),
        },
        'AnalogOutputs': {'Vs': 'ao1',
                          'Vds': 'ao0',
                          },
        }

MainBoard_v3 = {'Gains': DefaultGains,
                'AnalogInputs': {'Ch01': ('ai8',),
                                 'Ch11': ('ai12',),
                                 'Ch03': ('ai9',),
                                 'Ch09': ('ai15',),
                                 'Ch05': ('ai10',),
                                 'Ch15': ('ai14',),
                                 'Ch07': ('ai11',),
                                 'Ch13': ('ai13',),
                                 'Ch02': ('ai0',),
                                 'Ch12': ('ai4',),
                                 'Ch04': ('ai1',),
                                 'Ch10': ('ai7',),
                                 'Ch06': ('ai2',),
                                 'Ch16': ('ai6',),
                                 'Ch08': ('ai3',),
                                 'Ch14': ('ai5',),
                                 'Ch27': ('ai27',),
                                 'Ch17': ('ai29',),
                                 'Ch25': ('ai26',),
                                 'Ch19': ('ai30',),
                                 'Ch31': ('ai25',),
                                 'Ch21': ('ai31',),
                                 'Ch29': ('ai24',),
                                 'Ch23': ('ai28',),
                                 'Ch28': ('ai19',),
                                 'Ch18': ('ai21',),
                                 'Ch26': ('ai18',),
                                 'Ch20': ('ai22',),
                                 'Ch32': ('ai17',),
                                 'Ch22': ('ai23',),
                                 'Ch30': ('ai16',),
                                 'Ch24': ('ai20',)
                                 },
                'AnalogOutputs': {'Vs': 'ao1',
                                  'Vds': 'ao0',
                                  'Vg': 'ao2',
                                  },
                'ACDCSwitch': {'douts': ('port0/line0:8',),
                               'states': {'DC': np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                                                         dtype=np.uint8),
                                          'AC': np.array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                                                         dtype=np.uint8),
                                          'Gate': np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                                                           dtype=np.uint8),
                                          },
                               'GateAI': 'ai27',
                               }
                }

MainBoard_v3_Mux = MainBoard_v3.copy()
MainBoard_v3_Mux['DigitalOutputs'] = GetDecoderSignal()

Boards = {'MainBoard_v3': MainBoard_v3,
          'MainBoard_v3_Mux': MainBoard_v3_Mux,
          'MainBoard': MainBoard,
          'MB42': MB42,
          }

#           'MainBoard_16x16': MainBoard_16x16,
#           'MainBoard_8x8': MainBoard_8x8,
#           'Mos2': Mos2,
#           'MB41': MB41,
#           'MB42': MB42,

# 'MainBoard_v3_mux': MainBoard_v3_mux,


# MainBoard_16x16 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
#                                   'Ch02': ('ai1', 'ai9'),
#                                   'Ch03': ('ai2', 'ai10'),
#                                   'Ch04': ('ai3', 'ai11'),
#                                   'Ch05': ('ai4', 'ai12'),
#                                   'Ch06': ('ai5', 'ai13'),
#                                   'Ch07': ('ai6', 'ai14'),
#                                   'Ch08': ('ai7', 'ai15'),
#                                   'Ch09': ('ai16', 'ai24'),
#                                   'Ch10': ('ai17', 'ai25'),
#                                   'Ch11': ('ai18', 'ai26'),
#                                   'Ch12': ('ai19', 'ai27'),
#                                   'Ch13': ('ai20', 'ai28'),
#                                   'Ch14': ('ai21', 'ai29'),
#                                   'Ch15': ('ai22', 'ai30'),
#                                   'Ch16': ('ai23', 'ai31')},

#                    'aoChannels': {'ChVs': 'ao1',
#                                   'ChVds': 'ao0',
#                                   'ChAo2': None,
#                                   'ChAo3': None, },

#                    'ColOuts': {'Col05': ('line0', 'line1'),
#                                'Col06': ('line2', 'line3'),
#                                'Col08': ('line4', 'line5'),
#                                'Col07': ('line6', 'line7'),
#                                'Col02': ('line8', 'line9'),
#                                'Col04': ('line10', 'line11'),
#                                'Col01': ('line12', 'line13'),
#                                'Col03': ('line14', 'line15'),
#                                'Col16': ('line16', 'line17'),
#                                'Col15': ('line18', 'line19'),
#                                'Col13': ('line20', 'line21'),
#                                'Col14': ('line22', 'line23'),
#                                'Col11': ('line24', 'line25'),
#                                'Col09': ('line26', 'line27'),
#                                'Col12': ('line28', 'line29'),
#                                'Col10': ('line30', 'line31'),
#                                },
#                    'DOSwitch': None,
#                    }

# MainBoard_8x8 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
#                                 'Ch02': ('ai1', 'ai9'),
#                                 'Ch03': ('ai2', 'ai10'),
#                                 'Ch04': ('ai3', 'ai11'),
#                                 'Ch05': ('ai4', 'ai12'),
#                                 'Ch06': ('ai5', 'ai13'),
#                                 'Ch07': ('ai6', 'ai14'),
#                                 'Ch08': ('ai7', 'ai15'),
#                                 'Ch09': ('ai16', 'ai24'),
#                                 'Ch10': ('ai17', 'ai25'),
#                                 'Ch11': ('ai18', 'ai26'),
#                                 'Ch12': ('ai19', 'ai27'),
#                                 'Ch13': ('ai20', 'ai28'),
#                                 'Ch14': ('ai21', 'ai29'),
#                                 'Ch15': ('ai22', 'ai30'),
#                                 'Ch16': ('ai23', 'ai31')},

#                  'aoChannels': {'ChVs': 'ao1',
#                                 'ChVds': 'ao0',
#                                 'ChAo2': None,
#                                 'ChAo3': None, },

#                  'ColOuts': {'Col01': ('line0', 'line1'),
#                              'Col02': ('line2', 'line3'),
#                              'Col03': ('line4', 'line5'),
#                              'Col04': ('line6', 'line7'),
#                              'Col05': ('line8', 'line9'),
#                              'Col06': ('line10', 'line11'),
#                              'Col07': ('line12', 'line13'),
#                              'Col08': ('line14', 'line15'),
#                              },
#                  'DOSwitch': None,
#                  }

# Mos2 = {'aiChannels': {'Ch01': ('ai0', 'ai8'),
#                        'Ch02': ('ai1', 'ai9'),
#                        'Ch03': ('ai2', 'ai10'),
#                        'Ch04': ('ai3', 'ai11'),
#                        'Ch05': ('ai4', 'ai12'),
#                        'Ch06': ('ai5', 'ai13'),
#                        'Ch07': ('ai6', 'ai14'),
#                        'Ch08': ('ai7', 'ai15'),
#                        'Ch09': ('ai16', 'ai24'),
#                        'Ch10': ('ai17', 'ai25'),
#                        'Ch11': ('ai18', 'ai26'),
#                        'Ch12': ('ai19', 'ai27'),
#                        'Ch13': ('ai20', 'ai28'),
#                        'Ch14': ('ai21', 'ai29'),
#                        'Ch15': ('ai22', 'ai30'),
#                        'Ch16': ('ai23', 'ai31')},

#         'aoChannels': {'ChVs': 'ao1',
#                        'ChVds': 'ao0',
#                        'ChAo2': 'ao2',
#                        'ChAo3': 'ao3', },

#         'ColOuts': {'Col04': ('line0', ),
#                     'Col01': ('line1', ),
#                     'Col02': ('line2', ),
#                     'Col03': ('line3', ),
#                     'Col08': ('line4', ),
#                     'Col05': ('line5', ),
#                     'Col07': ('line6', ),
#                     'Col06': ('line7', ),
#                     'Col09': ('line8', ),
#                     'Col12': ('line9', ),
#                     'Col11': ('line10', ),
#                     'Col10': ('line11', ),
#                     'Col13': ('line12', ),
#                     'Col16': ('line13', ),
#                     'Col15': ('line14', ),
#                     'Col14': ('line15', ),
#                     },
#         'DOSwitch': None,
#         }

# MB41 = {'aiChannels': {'Ch09': ('ai0', 'ai8'),
#                        'Ch10': ('ai1', 'ai9'),
#                        'Ch11': ('ai2', 'ai10'),
#                        'Ch12': ('ai3', 'ai11'),
#                        'Ch13': ('ai4', 'ai12'),
#                        'Ch14': ('ai5', 'ai13'),
#                        'Ch15': ('ai6', 'ai14'),
#                        'Ch16': ('ai7', 'ai15'),
#                        'Ch01': ('ai16', 'ai24'),
#                        'Ch02': ('ai17', 'ai25'),
#                        'Ch03': ('ai18', 'ai26'),
#                        'Ch04': ('ai19', 'ai27'),
#                        'Ch05': ('ai20', 'ai28'),
#                        'Ch06': ('ai21', 'ai29'),
#                        'Ch07': ('ai22', 'ai30'),
#                        'Ch08': ('ai23', 'ai31'),
#                        },

#         'aoChannels': {'ChVs': 'ao1',
#                        'ChVds': 'ao0',
#                        'ChAo2': None,
#                        'ChAo3': None, },

#         'ColOuts': {'Col10': ('line0', 'line1'),
#                     'Col09': ('line2', 'line3'),
#                     'Col12': ('line4', 'line5'),
#                     'Col11': ('line6', 'line7'),
#                     'Col15': ('line8', 'line9'),
#                     'Col16': ('line10', 'line11'),
#                     'Col13': ('line12', 'line13'),
#                     'Col14': ('line14', 'line15'),
#                     'Col02': ('line16', 'line17'),
#                     'Col01': ('line18', 'line19'),
#                     'Col04': ('line20', 'line21'),
#                     'Col03': ('line22', 'line23'),
#                     'Col07': ('line24', 'line25'),
#                     'Col08': ('line26', 'line27'),
#                     'Col05': ('line28', 'line29'),
#                     'Col06': ('line30', 'line31'),
#                     },
#         'DOSwitch': None,
#         }

# MB42 = {'aiChannels': {'Ch09': ('ai0', 'ai8'),
#                        'Ch10': ('ai1', 'ai9'),
#                        'Ch11': ('ai2', 'ai10'),
#                        'Ch12': ('ai3', 'ai11'),
#                        'Ch13': ('ai4', 'ai12'),
#                        'Ch14': ('ai5', 'ai13'),
#                        'Ch15': ('ai6', 'ai14'),
#                        'Ch16': ('ai7', 'ai15'),
#                        'Ch01': ('ai16', 'ai24'),
#                        'Ch02': ('ai17', 'ai25'),
#                        'Ch03': ('ai18', 'ai26'),
#                        'Ch04': ('ai19', 'ai27'),
#                        'Ch05': ('ai20', 'ai28'),
#                        'Ch06': ('ai21', 'ai29'),
#                        'Ch07': ('ai22', 'ai30'),
#                        'Ch08': ('ai23', 'ai31'),
#                        },

#         'aoChannels': {'ChVs': 'ao1',
#                        'ChVds': 'ao0',
#                        'ChAo2': None,
#                        'ChAo3': None, },

#         'ColOuts':  {'Col10': ('line0', ),
#                      'Col09': ('line1', ),
#                      'Col12': ('line2', ),
#                      'Col11': ('line3', ),
#                      'Col15': ('line4', ),
#                      'Col16': ('line5', ),
#                      'Col13': ('line6', ),
#                      'Col14': ('line7', ),
#                      'Col02': ('line8', ),
#                      'Col01': ('line9', ),
#                      'Col04': ('line10', ),
#                      'Col03': ('line11', ),
#                      'Col07': ('line12', ),
#                      'Col08': ('line13', ),
#                      'Col05': ('line14', ),
#                      'Col06': ('line15', ),
#                      },

#         'DOSwitch': None,
#         }


# MainBoard_v3_mux = {'aiChannels': {'Ch01': 'ai8',
#                                    'Ch11': 'ai12',
#                                    'Ch03': 'ai9',
#                                    'Ch09': 'ai15',
#                                    'Ch05': 'ai10',
#                                    'Ch15': 'ai14',
#                                    'Ch07': 'ai11',
#                                    'Ch13': 'ai13',
#                                    'Ch02': 'ai0',
#                                    'Ch12': 'ai4',
#                                    'Ch04': 'ai1',
#                                    'Ch10': 'ai7',
#                                    'Ch06': 'ai2',
#                                    'Ch16': 'ai6',
#                                    'Ch08': 'ai3',
#                                    'Ch14': 'ai5',
#                                    'Ch27': 'ai27',
#                                    'Ch17': 'ai29',
#                                    'Ch25': 'ai26',
#                                    'Ch19': 'ai30',
#                                    'Ch31': 'ai25',
#                                    'Ch21': 'ai31',
#                                    'Ch29': 'ai24',
#                                    'Ch23': 'ai28',
#                                    'Ch28': 'ai19',
#                                    'Ch18': 'ai21',
#                                    'Ch26': 'ai18',
#                                    'Ch20': 'ai22',
#                                    'Ch32': 'ai17',
#                                    'Ch22': 'ai23',
#                                    'Ch30': 'ai16',
#                                    'Ch24': 'ai20'},

#                     'aoChannels': {'ChVs': 'ao1',
#                                    'ChVds': 'ao0',
#                                    'ChAo2': None,
#                                    'ChAo3': None, },

#                     'ColOuts': {'Col01': None,
#                                 'Col02': None,
#                                 'Col03': None,
#                                 'Col04': None,
#                                 'Col05': None,
#                                 'Col06': None,
#                                 'Col07': None,
#                                 'Col08': None,
#                                 'Col09': None,
#                                 'Col10': None,
#                                 'Col11': None,
#                                 'Col12': None,
#                                 'Col13': None,
#                                 'Col14': None,
#                                 'Col15': None,
#                                 'Col16': None,
#                                 'Col17': None,
#                                 'Col18': None,
#                                 'Col19': None,
#                                 'Col20': None,
#                                 'Col21': None,
#                                 'Col22': None,
#                                 'Col23': None,
#                                 'Col24': None,
#                                 'Col25': None,
#                                 'Col26': None,
#                                 'Col27': None,
#                                 'Col28': None,
#                                 'Col29': None,
#                                 'Col30': None,
#                                 'Col31': None,
#                                 'Col32': None,
#                                 },
#                     'DOSwitch': ['port0/line0:8', ],
#                     }


# if __name__ == '__main__':
#     print('gg')
